### ISSUE TITLE
question regarding test signature

### ISSUE THREAD

**Issue by Mouvedia** [feus4177/cupping#1]
> `test(name, fn)`

1. Can you support promises for the second parameter?

```
test(String, Function | Promise)
```

2. Can you support arrays of functions/promises?

e.g. `[fn, promise]` would require that both the function and promise be "marked as succeeded" for the test to pass.

```
test(String, [Function | Promise])

**Comment by feus4177** [comment]
Yeah, I would be open to allowing a function or a promise. I don't think I see a strong argument for allowing an array though.

**Comment by Mouvedia** [comment]
> I don't think I see a strong argument for allowing an array though.

It's useful when you wanna share multiple partial checks between tests.
Clearly if you don't have a big and consistent code base you won't see the appeal.

> I would be open to allowing a function or a promise

That's good enough.

**Comment by feus4177** [comment]
Could you share an example use case of passing an array?

**Comment by Mouvedia** [comment]
Nop sorry. But I have a feature request; Ill open a new issue.

**Comment by feus4177** [comment]
I've modified the code to support a promise in addition to a function.

It's too bad you can't think of an example for passing an array. Maybe I'm just not understanding what you're saying or perhaps this would be something I could supply a utility function for. If you think of something, I can reopen this ticket.
