### ISSUE TITLE
feature request: steps

### ISSUE THREAD

**Issue by Mouvedia** [feus4177/cupping#2]
Could you add something like [mocha-steps](https://github.com/rprieto/mocha-steps)?

```
step/xstep(String, Function);
```

You already have `serial` but that's not exactly it. Maybe you could improve it?

**Comment by feus4177** [comment]
Yeah, I see what you're saying. I changed it so that the promise returned by the test methods will reject if a test case fails. So now to emulate mocha-steps you can do the following:

```javascript
const cup = require('../index.js');

cup.test('login', () => {
    console.log('whatever');
}).then(() => cup.test('buy an item', () => {
    throw new Error('failed');
})).then(() => cup.test('check my balance', () => {
    console.log('will not run');
}));
```
